$Lab="asr"
$Region="WestUS"
$User="student-lab-01@labscloudacademy.onmicrosoft.com"
$Pass="labAccount1"
$PolicyDefinitionName="lab-policy"
$PolicyAssignmentName="lab-policy-assignment"
$RoleDefinitionName="Lab Role"